channels:
- defaults
dependencies:
- mkl=2017.0.3=0
- numpy=1.11.3=py34_0
- pip=9.0.1=py34_1
- python=3.4.5=0
- wheel=0.29.0=py34_0
- pip:
  - backports-abc==0.5
  - bleach==2.0.0
  - https://cntk.ai/PythonWheel/GPU-1bit-SGD/cntk-2.1-cp34-cp34m-linux_x86_64.whl
  - colorama==0.3.9
  - cycler==0.10.0
  - decorator==4.1.2
  - easydict==1.7
  - entrypoints==0.2.3
  - future==0.16.0
  - html5lib==0.999999999
  - ipykernel==4.6.1
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - ipywidgets==6.0.0
  - jedi==0.10.2
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - markupsafe==1.0
  - matplotlib==2.0.2
  - mistune==0.7.4
  - nbconvert==5.2.1
  - nbformat==4.3.0
  - networkx==1.11
  - notebook==5.0.0
  - olefile==0.44
  - pandocfilters==1.4.2
  - pickleshare==0.7.4
  - pillow==4.2.1
  - prompt-toolkit==1.0.15
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pywavelets==0.5.2
  - pyzmq==16.0.2
  - qtconsole==4.3.1
  - scikit-learn==0.19.0
  - simplegeneric==0.8.1
  - six==1.10.0
  - testpath==0.3.1
  - tornado==4.5.1
  - traitlets==4.3.2
  - typing==3.6.2
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - widgetsnbextension==2.0.0
  - win-unicode-console==0.5
  - xmltodict==0.11.0

